; Generic ESP32-S3 + SX1276 – DIY variant
; Adjust pins in variant.h to match your wiring.

[env:generic-esp32s3-sx1276]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_level = extra
upload_protocol = esptool
upload_speed = 921600
build_unflags =
  ${esp32s3_base.build_unflags}
  -D ARDUINO_USB_MODE=1
build_flags =
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32s3/diy/generic_esp32s3_sx1276
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -ULED_BUILTIN
